
language: node_js

node_js:
 - stable

branches:
  only:
  - master

before_install:
  - npm install -g cnpm --registry=https://registry.npm.taobao.org
  - cnpm i -g yarn
  
install:
  - cnpm install

script:
 - cnpm run build